//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeworkNo1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class 客戶聯絡人
    {
        public int Id { get; set; }
        public int 客戶Id { get; set; }

        [Required(ErrorMessage = "請輸入職稱！")]
        [StringLength(50, ErrorMessage = "職稱最多輸入 50 個字！")]
        public string 職稱 { get; set; }

        [Required(ErrorMessage = "請輸入姓名！")]
        [StringLength(50, ErrorMessage = "姓名最多輸入 50 個字！")]
        public string 姓名 { get; set; }

        [Required(ErrorMessage = "請輸入 EMail！")]
        [StringLength(250, ErrorMessage = "EMail 最多輸入 250 個字！")]
        [RegularExpression(@"^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "EMail 格式錯誤！")]
        public string Email { get; set; }

        [RegularExpression(@"09\d{2}-\d{6}", ErrorMessage = "手機格式為 0912-345678！")]
        public string 手機 { get; set; }

        [StringLength(50, ErrorMessage = "電話最多輸入 50 個字！")]
        public string 電話 { get; set; }
    
        public virtual 客戶資料 客戶資料 { get; set; }
    }
}
